name: foodiefit
description: "A Flutter app for tracking food and fitness."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  http: ^1.2.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  mobile_scanner: ^5.2.3
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.1
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
