name: foodiefit
description: "A Flutter app for tracking food and fitness."
publish_to: "none"
version: 0.1.0-beta.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^1.1.1
  http: ^1.2.2
  image_picker: ^1.0.7
  intl: ^0.20.2
  mobile_scanner: ^7.1.3
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.1
  shared_preferences: ^2.2.2
  openfoodfacts: ^3.1.0
  share_plus: ^12.0.1
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/icon.png
    - assets/icon/splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/splash.png
  android: true
  ios: true
  web: true
  android_12:
    image: assets/icon/splash.png
    icon_background_color: "#FFFFFF"
